### ISSUE TITLE
GUI freezes on boot Dual Pentium 3

### ISSUE THREAD

**Issue by RockeyDA** [klange/ponyos#10]
dose this need sse2 or somthing? i have not had luck getting the graphical part of the os to boot on my Pentium 3 server. 
specs: dual 550mhz pentium 3's 1gb pc100 ram, voodoo fx 3, soundblaster awe64, ibm model F over usb tensy bored.

**Comment by klange** [comment]
SSE2 is required to run the GUI. P4 at minimum, mostly due to the choice of optimization target at compile time. Sorry!
