### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by GSH-sc** [klange/ponyos#11]
I've not found at 4.0 CD the install menu. Is it existing? And does the distro have a root console or something similar?

**Comment by klange** [comment]
There is no installer for PonyOS; it is only available as a live CD.

> distro

PonyOS is not a "distro".

> root console

I'm not sure what you mean by this. A terminal-only interface is available from the boot menu, but there is no concept of a "root console" in the OS. A VGA text-mode terminal emulator is provided, but as PonyOS is an inherently graphical operating system it is not recommended.
