### ISSUE TITLE
[Feature request] Ponysay built in to ponyos

### ISSUE THREAD

**Issue by stonewareslord** [klange/ponyos#3]
This application: 
https://github.com/erkin/ponysay
Should be built-in to this OS.

**Comment by WST** [comment]
Sure! I also suggest http://www.ponylang.org/ for truly pony-way app development.

**Comment by WST** [comment]
Any explainations? Is it finished? Rejected?

**Comment by klange** [comment]
Patience. Good things come to Ponies who wait.

**Comment by klange** [comment]
![](http://i.imgur.com/aQcD6A1.png)

**Comment by WST** [comment]
Thank you very much ^_^
You’ve made Apple Bloom jumping because of happiness :3
