### ISSUE TITLE
When compiling, get errors

### ISSUE THREAD

**Issue by vincenzofehring** [klange/ponyos#5]
I get the following error when I try to run "make" on the source code.

/7802533/c87683bc-02ec-11e5-9c7c-51fd64237f93.png)
ctag  Generating CTags...! Fatal error encountered.
/bin/sh: 1: ctags: not found
make: [tags] Error 1 (ignored)
  ctag  Generated CTags.
/bin/sh: 1: ctags: not found

![screenshot from 2015-05-25 14 45 59](https://cloud.githubusercontent.com/assets/671972

**Comment by vincenzofehring** [comment]
![screenshot from 2015-05-25 14 45 59](https://cloud.githubusercontent.com/assets/671972/7802535/da65bb42-02ec-11e5-87ed-897209dfb121.png)

**Comment by klange** [comment]
You are missing `ctags`, but this build step happens after everything else has finished. This isn't a problem.
