### ISSUE TITLE
Cannot compile: “/bin/sh: 1: ctags: not found”

### ISSUE THREAD

**Issue by ProgVal** [klange/ponyos#7]
```
  yasm  kernel/symbols.s
   CC   kernel/start.o
   --   Kernel is ready!
  ctag  Generating CTags...! Fatal error encountered.
/bin/sh: 1: ctags: not found
Makefile:246: recipe for target 'tags' failed
make: [tags] Error 1 (ignored)
  ctag  Generated CTags.
/bin/sh: 1: ctags: not found
progval@ion:~/ponyos$ exit
root@ion:/home/progval/ponyos# aptitude show exuberant-ctags
Package: exuberant-ctags                 
State: installed
[…]
```

This is a fresh Debian 8.2 system (with git, python3, and make installed).

**Comment by klange** [comment]
It looks like the `exuberant-ctags` package in Debian only provides an [`exuberant-ctags` binary](https://packages.debian.org/sid/i386/exuberant-ctags/filelist) and not a `ctags`. But this is only a warning (`Error 1 (ignored)`). Additionally, this is not an issue with PonyOS, but an upstream issue with ToaruOS that has already been reported and marked as WONTFIX.
