### ISSUE TITLE
generated .img is not recognized as a bootable disk by qemu

### ISSUE THREAD

**Issue by ProgVal** [klange/ponyos#8]
I get the following error:

![“Boot failed: not a bootable disk”](https://cloud.githubusercontent.com/assets/406946/12237577/b2cdfcea-b87f-11e5-8cf1-bdb7c02e29e2.png)

I used this command to run it: `qemu-system-i386 -m 1024 -hda toaruos-disk.img -vga std -sdl` (after `make toolchain` and `make`)

**Comment by klange** [comment]
The image built by the standard toolchain explicitly *isn't* a bootable disk. Look at the various `make` targets for running QEMU, such as `make run`/`make kvm`.
