### ISSUE TITLE
Supported Filesystems?

### ISSUE THREAD

**Issue by TekuSP** [klange/ponyos#9]
What are supported filesystems? NTFS? FAT32? EXT?

**Comment by klange** [comment]
Issue reports are not places to ask questions. PonyOS has only ever shipped with EXT2 support, but the upstream project also has ISO9660.

**Comment by TekuSP** [comment]
Can I create one? Like for FAT32 or FAT16?

**Comment by klange** [comment]
You are free to do whatever you wish under the terms of the license. If you wish to implement features for PonyOS, you would be better of doing so by implementing them upstream in [ToaruOS](https://github.com/klange/toaruos), as PonyOS itself is only an occasionally-released reskin.
